#!/usr/bin/env python3
"""Assemble the single source of truth (data.js) from the per-subject JSON files.

Run:  python3 build_data.py
Output: ./data.js  and prints a SHA-256 of the canonical JSON payload.
"""
import datetime
import hashlib
import re
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")
OUT_DIR = HERE  # data.js sits next to index.html so GitHub Pages serves it

ORDER = [
    "english-language",
    "english-literature",
    "maths",
    "biology",
    "chemistry",
    "physics",
    "geography",
    "spanish",
]

REQUIRED_SUBJECT_KEYS = {
    "id", "name", "board", "boardVerified", "boardNote",
    "specCode", "tier", "accent", "papers", "pastPapers", "resources", "topics",
    "exams", "examNote",
}

DATE_RE = re.compile(r"^20\d\d-\d\d-\d\d$")


def load_subject(sid):
    path = os.path.join(SRC, sid + ".json")
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    missing = REQUIRED_SUBJECT_KEYS - set(data)
    if missing:
        sys.exit("ERROR %s missing keys: %s" % (sid, sorted(missing)))
    if data["id"] != sid:
        sys.exit("ERROR %s has mismatched id %r" % (sid, data["id"]))
    seen = set()
    for topic in data["topics"]:
        for key in ("id", "name", "subtopics", "cards", "cloze"):
            if key not in topic:
                sys.exit("ERROR %s topic %r missing %r" % (sid, topic.get("name"), key))
        if topic["id"] in seen:
            sys.exit("ERROR duplicate topic id %s in %s" % (topic["id"], sid))
        seen.add(topic["id"])
        if not topic["subtopics"]:
            sys.exit("ERROR %s topic %s has no subtopics" % (sid, topic["id"]))
    if not data["exams"]:
        sys.exit("ERROR %s has no exams listed" % sid)
    for exam in data["exams"]:
        for key in ("code", "name", "date", "session", "duration"):
            if key not in exam:
                sys.exit("ERROR %s exam %r missing %r" % (sid, exam.get("code"), key))
        if not DATE_RE.match(exam["date"]):
            sys.exit("ERROR %s exam %s has bad date %r" % (sid, exam["code"], exam["date"]))
        try:
            datetime.date(*[int(p) for p in exam["date"].split("-")])
        except ValueError:
            sys.exit("ERROR %s exam %s date is not a real date" % (sid, exam["code"]))
    return data


def main():
    subjects = [load_subject(sid) for sid in ORDER]

    payload = {
        "schemaVersion": 2,
        "title": "GCSE Year 11 Revision Dashboard",
        "school": "King Edward VI Five Ways School, Birmingham",
        "curriculumSource": "https://www.kefw.org/academic/curriculum/",
        "academicYear": "Year 11, academic year 2026 to 2027",
        "boardVerificationNote": (
            "KEFW does not publish a consolidated exam-board list on its curriculum or "
            "subjects pages. Boards below marked verified were confirmed from the KEFW "
            "Curriculum Intent PDFs. Boards marked unverified are provisional and must be "
            "confirmed with the school before past papers are used."
        ),
        "examSeries": {
            "name": "Summer 2027 (June series)",
            "firstExam": "2027-05-10",
            "lastExam": "2027-06-18",
            "contingencyDay": "2027-06-23",
            "resultsDay": "2027-08-19",
            "source": "https://www.jcq.org.uk/wp-content/uploads/sites/2/2026/05/Key_Dates_June2027_FINAL.pdf",
            "note": (
                "National common-timetable dates from JCQ key dates for the June 2027 series. "
                "Per-paper dates come from the AQA (provisional v1.0, January 2026) and "
                "Pearson Edexcel provisional summer 2027 timetables and can still move."
            ),
        },
        "subjects": subjects,
    }

    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    payload["dataChecksum"] = digest

    pretty = json.dumps(payload, indent=2, ensure_ascii=True)

    os.makedirs(OUT_DIR, exist_ok=True)
    out_js = os.path.join(OUT_DIR, "data.js")
    with open(out_js, "w", encoding="utf-8") as fh:
        fh.write("/* GCSE Year 11 Revision Dashboard - SINGLE SOURCE OF TRUTH\n")
        fh.write(" * Generated by build_data.py from src/*.json. Do not hand-edit.\n")
        fh.write(" * Consumed identically by index.html, study.html and make_flashcards.py.\n")
        fh.write(" * SHA-256 of canonical payload: %s\n" % digest)
        fh.write(" */\n")
        fh.write("const GCSE_DATA = ")
        fh.write(pretty)
        fh.write(";\n")
        fh.write("if (typeof module !== 'undefined') { module.exports = GCSE_DATA; }\n")

    topics = sum(len(s["topics"]) for s in subjects)
    subtopics = sum(len(t["subtopics"]) for s in subjects for t in s["topics"])
    cards = sum(len(t["cards"]) for s in subjects for t in s["topics"])
    cloze = sum(len(t["cloze"]) for s in subjects for t in s["topics"])

    print("Wrote %s" % out_js)
    print("subjects=%d topics=%d subtopics=%d basic_cards=%d cloze_cards=%d total_cards=%d"
          % (len(subjects), topics, subtopics, cards, cloze, cards + cloze))
    print("checksum=%s" % digest)


if __name__ == "__main__":
    main()
