#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate STUDY_MATRIX.md (Deliverable 1) from data.js.

Standard library only. The matrix is generated, never hand-written, so it can
never disagree with the dashboard, the study companion or the Anki decks.

    python3 make_matrix.py            # writes ./STUDY_MATRIX.md
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_flashcards import load_data, default_data_path, payload_checksum  # noqa: E402


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def main():
    data = load_data(default_data_path())
    out = []
    a = out.append

    a("# Deliverable 1 - Topic Breakdown and Study Matrix")
    a("")
    a("**School:** %s  " % data["school"])
    a("**Year:** %s  " % data["academicYear"])
    a("**Curriculum source:** <%s>  " % data["curriculumSource"])
    a("**Data checksum (SHA-256):** `%s`" % payload_checksum(data))
    a("")
    a("> %s" % data["boardVerificationNote"])
    a("")
    a("Legend: :white_check_mark: board confirmed against the KEFW published examination boards list.")
    a("")

    # ── Summary table ──
    a("## Subject summary")
    a("")
    a("| Subject | Exam board | Spec code | Tier | Topics | Sub-topics | Cards | Official past papers | Free revision resource |")
    a("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for s in data["subjects"]:
        flag = ":white_check_mark:" if s["boardVerified"] else ":warning:"
        subs = sum(len(t["subtopics"]) for t in s["topics"])
        cards = sum(len(t["cards"]) + len(t["cloze"]) for t in s["topics"])
        res = s["resources"][0]
        a("| **%s** | %s %s | %s | %s | %d | %d | %d | [%s](%s) | [%s](%s) |" % (
            cell(s["name"]), flag, cell(s["board"]), cell(s["specCode"]), cell(s["tier"]),
            len(s["topics"]), subs, cards,
            "Past papers and mark schemes", s["pastPapers"]["url"],
            cell(res["label"]), res["url"]))
    a("")

    # ── Per-subject detail ──
    for s in data["subjects"]:
        flag = ":white_check_mark:" if s["boardVerified"] else ":warning:"
        a("## %s" % s["name"])
        a("")
        a("| Field | Value |")
        a("| --- | --- |")
        a("| Exam board | %s %s |" % (flag, cell(s["board"])))
        a("| Spec code | `%s` |" % cell(s["specCode"]))
        a("| Tier | %s |" % cell(s["tier"]))
        a("| Assessment | %s |" % cell(s["papers"]))
        a("| Official past papers | [%s](%s) |" % (cell(s["pastPapers"]["label"]), s["pastPapers"]["url"]))
        if s.get("altPastPapers"):
            a("| Alternative board papers | [%s](%s) |" % (cell(s["altPastPapers"]["label"]), s["altPastPapers"]["url"]))
        a("| Free revision resources | %s |" % " &middot; ".join(
            "[%s](%s)" % (cell(r["label"]), r["url"]) for r in s["resources"]))
        a("| Board verification | %s |" % cell(s["boardNote"]))
        a("")
        a("| Topic | Core sub-topics | Cards |")
        a("| --- | --- | --- |")
        for t in s["topics"]:
            a("| **%s** | %s | %d basic + %d cloze |" % (
                cell(t["name"]),
                "<br>".join("- " + cell(x) for x in t["subtopics"]),
                len(t["cards"]), len(t["cloze"])))
        a("")

    totals = (
        len(data["subjects"]),
        sum(len(s["topics"]) for s in data["subjects"]),
        sum(len(t["subtopics"]) for s in data["subjects"] for t in s["topics"]),
        sum(len(t["cards"]) for s in data["subjects"] for t in s["topics"]),
        sum(len(t["cloze"]) for s in data["subjects"] for t in s["topics"]),
    )
    a("## Totals")
    a("")
    a("%d subjects &middot; %d topics &middot; %d trackable sub-topics &middot; %d basic flashcards &middot; %d cloze flashcards" % totals)
    a("")
    a("This file is generated by `make_matrix.py` from `data.js`, the single source of truth also consumed by `index.html`, `study.html` and `make_flashcards.py`.")
    a("")

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "STUDY_MATRIX.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print("Wrote %s (%d lines)" % (path, len(out)))


if __name__ == "__main__":
    main()
